"""add quiz visibility

Revision ID: 2c56e3574250
Revises: dfbc7777a976
Create Date: 2026-08-21 19:59:59.867951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c56e3574250'
down_revision: Union[str, Sequence[str], None] = 'dfbc7777a976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('visibility', sa.String(length=20), server_default=sa.text("'unlisted'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'visibility')
    # ### end Alembic commands ###
