"""add ai explanations and whiteboard images

Revision ID: 2e978ba2fe77
Revises: 169c96268a60
Create Date: 2026-08-24 16:03:01.197981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e978ba2fe77'
down_revision: Union[str, Sequence[str], None] = '169c96268a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempt_answers', sa.Column('ai_explanation', sa.Text(), nullable=True))
    op.add_column('quiz_attempt_answers', sa.Column('whiteboard_image_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_attempt_answers', 'whiteboard_image_url')
    op.drop_column('quiz_attempt_answers', 'ai_explanation')
    # ### end Alembic commands ###
