"""add quiz icon

Revision ID: 83aafbec409b
Revises: 7340b79137d6
Create Date: 2026-08-24 19:44:24.342892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83aafbec409b'
down_revision: Union[str, Sequence[str], None] = '7340b79137d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('icon', sa.String(length=50), server_default=sa.text("'file-question'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'icon')
    # ### end Alembic commands ###
