"""add expected answer to questions

Revision ID: dfbc7777a976
Revises: 07401dade95d
Create Date: 2026-08-18 16:59:24.209760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfbc7777a976'
down_revision: Union[str, Sequence[str], None] = '07401dade95d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('expected_answer', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'expected_answer')
    # ### end Alembic commands ###
